import polars as pl
INITIAL_COLS = [
    # "Product",
    # "Symbool | ISIN",
    "ISIN",
    "Beurs",
    "SECURITY_TYPE",
    "HEFBOOM",
    "STOPLOSS",
    "Aantal",
    "Koers",
    "Valuta",
    "INITIELE_WAARDE",
    "Waarde",
    "GAK",
    "W/V\xa0€",
    "W/V %",
    "ONGEREALISEERDE_WV_EUR",
    "ONGEREALISEERDE_WV_PCT",
    # "Totale W/V€",
    
]

CASH_SCHEMA = {   
    "ISIN": pl.Utf8, 
    "Beurs": pl.Utf8,
    "SECURITY_TYPE": pl.Utf8,
    "HEFBOOM": pl.Float64,
    "STOPLOSS": pl.Float64,
    "Aantal": pl.Float64,
    "Koers": pl.Utf8,
    "Valuta": pl.Utf8,
    "INITIELE_WAARDE": pl.Float64,
    "Waarde": pl.Float64,
    "GAK": pl.Float64,
    "W/V\xa0€": pl.Float64,
    "W/V %": pl.Utf8,
    "ONGEREALISEERDE_WV_EUR": pl.Float64,
    "ONGEREALISEERDE_WV_PCT": pl.Float64,
    "UNDERLYING_ISIN": pl.Utf8,
    "UNDERLYING": pl.Utf8,
    "SECTOR": pl.Utf8,
    "INDUSTRY": pl.Utf8,
}
